# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MongoDBLayerPlugin
                                 A QGIS plugin
 This plugin gives the possibility to create a layer from MongoDB datasource
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-02-17
        copyright            : (C) 2024 by Romain Bruyère
        email                : rom.bruyere@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MongoDBLayerPlugin class from file MongoDBLayerPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    if __name__ == '__main__':
        from core.mongodb_layer_plugin import MongoDBLayerPlugin
    else:
        from .core.mongodb_layer_plugin import MongoDBLayerPlugin
    return MongoDBLayerPlugin(iface)
